import fs from 'node:fs';
import path from 'node:path';

/**
 * Turns functions/go/redirect-map.json into a Caddyfile snippet for the /go/ redirects.
 *
 * Cloudflare Pages Functions (functions/go/[slug].ts) are Cloudflare-specific — they
 * won't run behind a plain Caddy server. The redirect logic itself is trivial (slug ->
 * 302), so a `redir` line per casino does the same job with no running process behind
 * it. Click counts become "grep /go/ out of the Caddy access log" instead of a
 * Cloudflare Analytics Engine dataset; see deploy/README.md for the one-liner.
 *
 * Regenerate on every deploy (a new casino or a changed affiliateUrl needs this to run
 * again) and reload Caddy afterwards — reload, not restart, so it never drops a
 * connection and re-validates the config before applying it.
 */
const redirectMapPath = path.join(process.cwd(), 'functions/go/redirect-map.json');
if (!fs.existsSync(redirectMapPath)) {
  console.error('build-caddy-redirects: functions/go/redirect-map.json not found. Run `npm run build` first.');
  process.exit(1);
}

const map = JSON.parse(fs.readFileSync(redirectMapPath, 'utf8')) as Record<
  string,
  { url: string; affiliate: boolean }
>;

// Caddyfile string values only need their own quotes escaped — no other templating
// concern the way a shell or nginx string would have.
const caddyQuote = (s: string): string => `"${s.replace(/"/g, '\\"')}"`;

const lines = Object.entries(map)
  .map(([slug, dest]) => `\tredir /go/${slug} ${caddyQuote(dest.url)} 302`)
  .join('\n');

const header = `# Generated by scripts/build-caddy-redirects.ts from functions/go/redirect-map.json.
# Do not edit by hand — regenerate on every deploy instead.
# Paste this block's contents inside the site's { } block in the Caddyfile, or
# \`import\` this file directly if the Caddyfile already imports from this directory.
`;

const body = `@go path /go/*
header @go X-Robots-Tag "noindex, nofollow"

${lines}
`;

const out = path.join(process.cwd(), 'deploy/go-redirects.caddy');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, `${header}\n${body}`);

console.log(`build-caddy-redirects: wrote ${Object.keys(map).length} redirects to ${out}`);
