import fs from 'node:fs';
import path from 'node:path';

/**
 * Turns functions/go/redirect-map.json into a plain nginx include file, so the /go/
 * redirects work on any nginx host, not just Cloudflare Pages.
 *
 * Cloudflare Pages Functions (functions/go/[slug].ts) are Cloudflare-specific — they
 * won't run on a generic VPS. The redirect logic itself is trivial (slug -> 302), so a
 * static nginx `location` block per casino does the same job with no running process
 * behind it. Click counts become "grep /go/ out of the nginx access log" instead of a
 * Cloudflare Analytics Engine dataset; see deploy/README.md for the one-liner.
 *
 * Regenerate on every deploy (a new casino or a changed affiliateUrl needs this to run
 * again) and reload nginx afterwards — reload, not restart, so it never drops a
 * connection.
 */
const redirectMapPath = path.join(process.cwd(), 'functions/go/redirect-map.json');
if (!fs.existsSync(redirectMapPath)) {
  console.error('build-nginx-redirects: functions/go/redirect-map.json not found. Run `npm run build` first.');
  process.exit(1);
}

const map = JSON.parse(fs.readFileSync(redirectMapPath, 'utf8')) as Record<
  string,
  { url: string; affiliate: boolean }
>;

const blocks = Object.entries(map)
  .map(
    ([slug, dest]) => `    location = /go/${slug} {
        add_header X-Robots-Tag "noindex, nofollow" always;
        return 302 ${JSON.stringify(dest.url)};
    }`,
  )
  .join('\n\n');

const header = `# Generated by scripts/build-nginx-redirects.ts from functions/go/redirect-map.json.
# Do not edit by hand — regenerate on every deploy instead.
# \`include\` this file inside the site's \`server { }\` block.
`;

const out = path.join(process.cwd(), 'deploy/go-redirects.conf');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, `${header}\n${blocks}\n`);

console.log(`build-nginx-redirects: wrote ${Object.keys(map).length} redirects to ${out}`);
