import fs from 'node:fs';
import path from 'node:path';

/**
 * Emits one complete, ready-to-append Caddyfile site block for gambleatlas.com.
 *
 * The VPS's existing /etc/caddy/Caddyfile is a flat file with no `import` directive —
 * every site is just another block appended after the last one. So rather than hand
 * two half-files (a static template plus a generated redirect snippet) for someone to
 * merge by hand, this writes the whole block in one shot: deploy the app with
 * `cat deploy/gambleatlas-site.caddy >> /etc/caddy/Caddyfile`, nothing to paste into
 * the middle of anything.
 *
 * The security headers and the _astro/* immutable-cache pattern mirror the existing
 * claudich.dev block on the same box, on the theory that whoever reads this Caddyfile
 * next should see one consistent house style, not a visibly different one bolted on.
 *
 * Cloudflare Pages Functions (functions/go/[slug].ts) are Cloudflare-specific and won't
 * run behind Caddy, so the /go/ redirects are reimplemented here as plain `redir`
 * lines from the same functions/go/redirect-map.json the Cloudflare path also reads —
 * one source of truth, two ways of serving it. Regenerate this file on every deploy (a
 * new casino or a changed affiliateUrl needs it) — see deploy/README.md for the append
 * + reload sequence.
 */
const CERT_EMAIL = 'sena4739686@gmail.com';

const redirectMapPath = path.join(process.cwd(), 'functions/go/redirect-map.json');
if (!fs.existsSync(redirectMapPath)) {
  console.error('build-caddy-site: functions/go/redirect-map.json not found. Run `npm run build` first.');
  process.exit(1);
}

const map = JSON.parse(fs.readFileSync(redirectMapPath, 'utf8')) as Record<
  string,
  { url: string; affiliate: boolean }
>;

// Caddyfile string values only need their own quotes escaped.
const q = (s: string): string => `"${s.replace(/"/g, '\\"')}"`;

const redirectLines = Object.entries(map)
  .map(([slug, dest]) => `\tredir /go/${slug} ${q(dest.url)} 302`)
  .join('\n');

const block = `# --- gambleatlas.com — generated by scripts/build-caddy-site.ts, do not hand-edit ---
# Regenerate and re-append (see deploy/README.md) instead of editing this block in
# place; the next regeneration would just overwrite hand edits anyway.
gambleatlas.com, www.gambleatlas.com {
\ttls ${CERT_EMAIL}

\tencode zstd gzip

\theader {
\t\tStrict-Transport-Security "max-age=31536000; includeSubDomains"
\t\tX-Content-Type-Options "nosniff"
\t\tX-Frame-Options "DENY"
\t\tReferrer-Policy "strict-origin-when-cross-origin"
\t\tPermissions-Policy "geolocation=(), camera=(), microphone=()"
\t}

\t@astroAssets path /_astro/*
\theader @astroAssets Cache-Control "public, max-age=31536000, immutable"

\troot * /var/www/gambleatlas/dist
\tfile_server

\t@go path /go/*
\theader @go X-Robots-Tag "noindex, nofollow"

${redirectLines}
}
# --- end gambleatlas.com ---
`;

const out = path.join(process.cwd(), 'deploy/gambleatlas-site.caddy');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, block);

console.log(
  `build-caddy-site: wrote gambleatlas.com block with ${Object.keys(map).length} redirects to ${out}`,
);
